name: Doxygen

on:
  push:
    branches:
      - master
      - ci-*

jobs:
  doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install deps
        run: |
          sudo apt install doxygen -y
          sudo npm install -g surge
      - name: fix
        run: |
          sed -i 's/!\[puffer\](.*?)//g' README.md
          sed -i 's|\[!\[\([^(]*\)\]([^)]*)|[\1|g' README.md
          sed -i 's|```c++|```{.cpp}|g' README.md
      - name: doxygen
        run: doxygen Doxyfile
      - name: upload
        run: surge ./doxygen/html protopuf.surge.sh --token ${{ secrets.SURGE_TOKEN }}
